"""
Report generator — turns a ScanResult into a structured Markdown report
and (optionally) a PDF via WeasyPrint.
"""
from datetime import datetime
from core.executor import ScanResult


SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

REMEDIATION_URGENCY = {
    "critical": "**Fix immediately.** This vulnerability is actively exploitable and poses immediate risk.",
    "high": "**Fix within 24 hours.** This vulnerability can be exploited with moderate effort.",
    "medium": "**Fix within 7 days.** This vulnerability requires specific conditions to exploit.",
    "low": "**Fix in next sprint.** Low-risk finding but worth addressing.",
}


def generate_markdown_report(scan: ScanResult) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = []

    # Header
    lines += [
        "# AI Security Assessment Report",
        f"**Target:** `{scan.target_endpoint}`",
        f"**Date:** {now}",
        f"**Scan ID:** `{scan.scan_id}`",
        f"**Duration:** {scan.duration_ms / 1000:.1f}s",
        "",
    ]

    # Executive summary
    lines += ["## Executive Summary", ""]
    if not scan.is_vulnerable:
        lines += [
            "✅ **No vulnerabilities detected** across all tested attack classes.",
            "",
            f"The target system was tested with {scan.total_attacks_run} attack scenarios "
            "and resisted all attempts. Continue regular testing as the AI threat landscape evolves.",
            "",
        ]
    else:
        lines += [
            f"⚠️ **{len(scan.findings)} vulnerabilities found** across {scan.total_attacks_run} tests.",
            "",
            f"| Severity | Count |",
            f"|----------|-------|",
            f"| 🔴 Critical | {scan.critical_count} |",
            f"| 🟠 High | {scan.high_count} |",
            f"| 🟡 Medium | {sum(1 for f in scan.findings if f.severity and f.severity.value == 'medium')} |",
            f"| 🔵 Low | {sum(1 for f in scan.findings if f.severity and f.severity.value == 'low')} |",
            "",
        ]

    # Target profile
    if scan.profile:
        p = scan.profile
        lines += [
            "## Target Profile",
            "",
            f"| Property | Detected Value |",
            f"|----------|----------------|",
            f"| Model Family | {p.model_family} |",
            f"| Framework | {p.framework} |",
            f"| System Prompt | {'Yes' if p.has_system_prompt else 'Not detected'} |",
            f"| Tool Access | {'Yes' if p.has_tools else 'No'} |",
            f"| RAG / Knowledge Base | {'Yes' if p.has_rag else 'No'} |",
            "",
        ]

    # Findings
    if scan.findings:
        lines += ["## Findings", ""]
        for i, finding in enumerate(scan.findings, 1):
            sev = finding.severity.value if finding.severity else "info"
            emoji = SEVERITY_EMOJI.get(sev, "⚪")
            urgency = REMEDIATION_URGENCY.get(sev, "")

            lines += [
                f"### {i}. {emoji} {finding.title}",
                "",
                f"**Severity:** {sev.upper()}  ",
                f"**Attack Class:** `{finding.attack_class}`  ",
                f"**Test Duration:** {finding.duration_ms}ms",
                "",
                "#### Description",
                finding.description,
                "",
                "#### Proof of Concept",
                "The following payload confirmed the vulnerability:",
                "```",
                finding.proof_of_concept,
                "```",
                "",
                "#### Evidence",
                "The target responded with:",
                "```",
                finding.evidence,
                "```",
                "",
                "#### Remediation",
                urgency,
                "",
                finding.remediation,
                "",
                "---",
                "",
            ]

    # Footer
    lines += [
        "## About This Report",
        "",
        "Generated by **Kaavish** — Automated Red Teaming for AI Systems.",
        "This report contains sensitive security information. Handle accordingly.",
        "",
        "*We break your AI before someone else does.*",
    ]

    return "\n".join(lines)


def generate_pdf_report(scan: ScanResult) -> bytes:
    """Convert the Markdown report to PDF. Requires WeasyPrint."""
    try:
        import markdown
        from weasyprint import HTML, CSS

        md_content = generate_markdown_report(scan)
        html_content = markdown.markdown(md_content, extensions=["tables", "fenced_code"])

        styled_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                   max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }}
            h1 {{ color: #c0392b; border-bottom: 2px solid #c0392b; padding-bottom: 8px; }}
            h2 {{ color: #2c3e50; margin-top: 32px; }}
            h3 {{ color: #34495e; }}
            table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
            th {{ background: #f5f5f5; }}
            code, pre {{ background: #f8f8f8; padding: 2px 6px; border-radius: 3px;
                        font-family: 'Courier New', monospace; font-size: 13px; }}
            pre {{ padding: 12px; overflow-x: auto; border-left: 3px solid #c0392b; }}
            hr {{ border: none; border-top: 1px solid #eee; margin: 24px 0; }}
        </style>
        </head>
        <body>{html_content}</body>
        </html>
        """
        return HTML(string=styled_html).write_pdf()
    except ImportError:
        # WeasyPrint not installed — return markdown as bytes
        return generate_markdown_report(scan).encode("utf-8")
